Catch 401 before changing/adding authentication headers
KNowledgeOnWebScale/solid-authentication-browser-extension pull request #27
Opened 2023-03-26 20:12 UTC by axellorreyne

2023-03-26 20:13 UTC, axellorreyne commented
This fixes #10

2023-03-27 05:49 UTC, pheyvaer requested changes
Can you update the [CHANGELOG](https://github.com/KNowledgeOnWebScale/solid-authentication-browser-extension/blob/main/CHANGELOG.md) as well?

2023-03-31 08:24 UTC, axellorreyne commented
> Can you update the [CHANGELOG](https://github.com/KNowledgeOnWebScale/solid-authentication-browser-extension/blob/main/CHANGELOG.md) as well?

CHANGELOG updated in dcaf02353dde90cedbbf90792b9bdae4a6617dc6

2023-03-31 08:43 UTC, pheyvaer approved these changes

2023-03-31 09:20 UTC, merged